### ISSUE TITLE
Add digits of pi task?

### ISSUE THREAD

**Issue by hanabi1224** [tczajka/bigint-benchmark-rs#1]
Hi, kudos to the great work!  It will be awesome to expand benchmark tasks with pidigits.

BTW, I happen to have some [benchmark](https://another-benchmarks-game.vercel.app/rust) code for pidigits benchmark game with both num-bigint ([1.rs](https://github.com/hanabi1224/Another-Benchmarks-Game/blob/main/bench/algorithm/pidigits/1.rs)) and ibig ([2.rs](https://github.com/hanabi1224/Another-Benchmarks-Game/blob/main/bench/algorithm/pidigits/2.rs)), please feel free to grab. 

Looking forward to more performance improvement!

**Comment by tczajka** [comment]
That is a good idea. Will do!

I would prefer to use a better algorithm so that it's comparable speed to the digits of e benchmark.

Looks like yours, and the original Computer Language Benchmarks Game, sum a simple Taylor series term by term, which will converge slowly for millions of digits compared to alternative algorithms.
